Added test reporter (#303)
* Added test reporter

* try again, yaml sucks

* wip

* Experiment

* Added task to upload trx results

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -5,6 +5,10 @@ name: Dotnet Build and Test
 
 on:
   workflow_call:
+  
+permissions:
+  contents: read
+  checks: write
 
 jobs:
   dotnet-macos:
@@ -35,7 +39,22 @@ jobs:
 
       - name: Test
         run: |
-          dotnet test ./Whisper.net.sln --no-build
+          dotnet test ./Whisper.net.sln --no-build  --logger "trx"
+          
+      - name: Test Reporter
+        uses: dorny/test-reporter@v1.9.1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Whisper.net MacOs Test Results
+          path: ./**/*.trx
+          reporter: dotnet-trx
+          
+      - name: Upload trx files
+        uses: actions/upload-artifact@v4
+        with:
+          name: test-results-macos
+          path: ./**/*.trx
+          retention-days: 7
 
   dotnet-windows:
     runs-on: windows-latest
@@ -65,8 +84,23 @@ jobs:
 
       - name: Test
         run: |
-          dotnet test ./Whisper.net.sln --no-build
+          dotnet test ./Whisper.net.sln --no-build --logger "trx"
+          
+      - name: Test Reporter
+        uses: dorny/test-reporter@v1.9.1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Whisper.net Windows Test Results
+          path: ./**/*.trx
+          reporter: dotnet-trx
 
+      - name: Upload trx files
+        uses: actions/upload-artifact@v4
+        with:
+          name: test-results-windows
+          path: ./**/*.trx
+          retention-days: 7
+        
   dotnet-linux:
     runs-on: ubuntu-latest
 
@@ -95,4 +129,20 @@ jobs:
 
       - name: Test
         run: |
-          dotnet test ./Whisper.net.sln --no-build
+          dotnet test ./Whisper.net.sln --no-build --logger "trx"
+                        
+      - name: Test Reporter
+        uses: dorny/test-reporter@v1.9.1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Whisper.net Linux Test Results
+          path: ./**/*.trx
+          reporter: dotnet-trx
+
+      - name: Upload trx files
+        uses: actions/upload-artifact@v4
+        with:
+          name: test-results-linux
+          path: ./**/*.trx
+          retention-days: 7
+        
